name: Release

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Package Name'
        required: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get package details
        id: details
        run: |
          PACKAGE_DIR="packages/${{ github.event.inputs.package_name }}"
          if [ ! -d "$PACKAGE_DIR" ]; then
            echo "Error: Package directory '$PACKAGE_DIR' does not exist."
            exit 1
          fi
          PACKAGE_NAME=$(node -pe "require('./$PACKAGE_DIR/package.json').name")
          PACKAGE_VERSION=$(node -pe "require('./$PACKAGE_DIR/package.json').version")
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating release for ${PACKAGE_NAME}@${PACKAGE_VERSION}..."
          gh release create "${PACKAGE_NAME}@${PACKAGE_VERSION}" \
            --title "${PACKAGE_NAME}@${PACKAGE_VERSION}" \
            --generate-notes
